# Generated by Django 4.1.7 on 2023-04-14 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey_base', '0001_initial'),
        ('question_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iquestion',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_base.isurvey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='QuestionTestSimpleEv',
            fields=[
                ('itestquestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='question_blocks.itestquestion')),
            ],
            options={
                'verbose_name': 'тестовый вопрос с выбором',
                'verbose_name_plural': 'тестовые вопросы с выбором',
                'db_table': 'question_test_simple_ev',
            },
            bases=('question_blocks.itestquestion', models.Model),
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
