# Generated by Django 4.1.7 on 2023-04-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_blocks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iquestion',
            options={'base_manager_name': 'non_polymorphic', 'verbose_name': 'вопрос (iquestion)', 'verbose_name_plural': 'все вопросы (iquestion)'},
        ),
        migrations.AlterModelOptions(
            name='questionsimple',
            options={'verbose_name': 'простой вопрос', 'verbose_name_plural': 'простые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questiontestsimpleev',
            options={'verbose_name': 'тестовый вопрос с выбором', 'verbose_name_plural': 'тестовые вопросы с выбором'},
        ),
    ]
