# Generated by Django 4.1.7 on 2023-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_blocks', '0003_alter_iquestion_options_alter_questionsimple_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iquestion',
            name='option_required_for_pass',
            field=models.BooleanField(default=False, verbose_name='Необходим при прохождении'),
        ),
    ]
