# Generated by Django 4.1.7 on 2023-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_blocks', '0004_iquestion_option_required_for_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iquestion',
            name='option_required_for_pass',
            field=models.BooleanField(blank=True, default=False, verbose_name='Необходим при прохождении'),
        ),
    ]
