# Generated by Django 4.1.7 on 2023-04-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'дополнительно о пользователе', 'verbose_name_plural': 'дополнительно о пользователях'},
        ),
    ]
