# Generated by Django 4.1.7 on 2023-04-14 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'ответ (ianswer)',
                'verbose_name_plural': 'ответы (ianswer)',
                'db_table': 'i_answer',
                'base_manager_name': 'non_polymorphic',
            },
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSelectableSimple',
            fields=[
                ('ianswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answer_blocks.ianswer')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
            ],
            options={
                'verbose_name': 'вариант ответа, простой',
                'verbose_name_plural': 'варианты ответа, простые',
                'db_table': 'answer_selectable_simple',
            },
            bases=('answer_blocks.ianswer', models.Model),
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IFreeAnswer',
            fields=[
                ('ianswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='answer_blocks.ianswer')),
            ],
            options={
                'verbose_name': 'без варианта ответа',
                'verbose_name_plural': 'без варианта ответа',
                'db_table': 'i_answer_free',
                'base_manager_name': 'non_polymorphic',
            },
            bases=('answer_blocks.ianswer', models.Model),
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
