# Generated by Django 4.1.7 on 2023-04-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_blocks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerselectablesimple',
            options={'verbose_name': 'вариант ответа, простой', 'verbose_name_plural': 'варианты ответа, простые'},
        ),
        migrations.AlterModelOptions(
            name='answerselectabletest',
            options={'verbose_name': 'вариант ответа, тест', 'verbose_name_plural': 'варианты ответа, тест'},
        ),
        migrations.AlterModelOptions(
            name='answertextinput',
            options={'verbose_name': 'поле ввода текста', 'verbose_name_plural': 'поля ввода текста'},
        ),
        migrations.AlterModelOptions(
            name='ianswer',
            options={'base_manager_name': 'non_polymorphic', 'verbose_name': 'ответ (ianswer)', 'verbose_name_plural': 'ответы (ianswer)'},
        ),
        migrations.AlterModelOptions(
            name='ifreeanswer',
            options={'base_manager_name': 'non_polymorphic', 'verbose_name': 'без варианта ответа', 'verbose_name_plural': 'без варианта ответа'},
        ),
    ]
