# Generated by Django 4.1.7 on 2023-05-03 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_blocks', '0002_initial'),
        ('survey_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_blocks.iquestion', verbose_name='Вопрос')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey_base.isurvey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'простая аналитика (SimpleAnalytics)',
                'verbose_name_plural': 'вся простая аналитика (SimpleAnalytics)',
                'db_table': 'SimpleAnalytics',
            },
        ),
    ]
