# Generated by Django 4.1.7 on 2023-04-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_passing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iresultanswer',
            options={'verbose_name': 'рез. ответ (i_result_answer)', 'verbose_name_plural': 'рез. ответы (i_result_answer)'},
        ),
        migrations.AlterModelOptions(
            name='resultselect',
            options={'verbose_name': 'выбранный ответ', 'verbose_name_plural': 'выбранные ответы'},
        ),
        migrations.AlterModelOptions(
            name='resulttextinput',
            options={'verbose_name': 'введённый текст', 'verbose_name_plural': 'введённые тексты'},
        ),
        migrations.AlterModelOptions(
            name='takingsurvey',
            options={'verbose_name': 'прождение всего опроса', 'verbose_name_plural': 'прохождения всего опроса'},
        ),
    ]
