# Generated by Django 4.1.7 on 2023-05-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_blocks', '0002_initial'),
        ('survey_passing', '0003_remove_iresultanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='iresultanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_blocks.iquestion', verbose_name='Вопрос'),
        ),
    ]
