# Generated by Django 4.1.7 on 2023-05-06 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_passing', '0006_iresultanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iresultanswer',
            name='question',
        ),
    ]
