# Generated by Django 4.1.7 on 2023-05-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_passing', '0007_remove_iresultanswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takingsurvey',
            name='time_passing',
        ),
    ]
