# Generated by Django 4.1.7 on 2023-05-07 12:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('survey_passing', '0008_remove_takingsurvey_time_passing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iresultanswer',
            options={'base_manager_name': 'non_polymorphic', 'verbose_name': 'рез. ответ (i_result_answer)', 'verbose_name_plural': 'рез. ответы (i_result_answer)'},
        ),
        migrations.AlterModelManagers(
            name='iresultanswer',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resultselect',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resulttextinput',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
