# Generated by Django 4.1.7 on 2023-04-29 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ISurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название опроса')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание опроса')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Был создан')),
                ('slug', models.SlugField(blank=True, max_length=108, null=True, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photos/isurvey/%Y/%m/%d/', verbose_name='фото к опросу')),
                ('option_is_published', models.BooleanField(blank=True, default=False, verbose_name='Публикация')),
                ('option_only_for_register_users', models.BooleanField(blank=True, default=False, verbose_name='Необходимость авторизации')),
                ('max_attempts', models.IntegerField(default=1, verbose_name='Максимальное число попыток')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'шапка опроса (isurvey)',
                'verbose_name_plural': 'все опросы (isurvey)',
                'db_table': 'i_survey',
            },
        ),
        migrations.CreateModel(
            name='SurveySimple',
            fields=[
                ('isurvey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey_base.isurvey')),
            ],
            options={
                'verbose_name': 'простой опрос',
                'verbose_name_plural': 'простые опросы',
                'db_table': 'survey_simple',
            },
            bases=('survey_base.isurvey', models.Model),
        ),
        migrations.CreateModel(
            name='SurveyTest',
            fields=[
                ('isurvey_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='survey_base.isurvey')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия теста')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания теста')),
                ('time_passing', models.IntegerField(blank=True, null=True, verbose_name='Время прохождения в минутах')),
            ],
            options={
                'verbose_name': 'тестовый опрос',
                'verbose_name_plural': 'тестовые опросы',
                'db_table': 'survey_test',
            },
            bases=('survey_base.isurvey', models.Model),
        ),
    ]
