# Generated by Django 4.1.7 on 2023-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isurvey',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='isurvey',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название опроса'),
        ),
    ]
