# Generated by Django 4.1.7 on 2023-04-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_base', '0002_isurvey_slug_alter_isurvey_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isurvey',
            options={'verbose_name': 'шапка опроса (isurvey)', 'verbose_name_plural': 'все опросы (isurvey)'},
        ),
        migrations.AlterModelOptions(
            name='surveysimple',
            options={'verbose_name': 'простой опрос', 'verbose_name_plural': 'простые опросы'},
        ),
        migrations.AlterModelOptions(
            name='surveytest',
            options={'verbose_name': 'тестовый опрос', 'verbose_name_plural': 'тестовые опросы'},
        ),
        migrations.AddField(
            model_name='isurvey',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='isurvey',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание опроса'),
        ),
        migrations.AlterField(
            model_name='isurvey',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='surveytest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания теста'),
        ),
        migrations.AlterField(
            model_name='surveytest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата открытия теста'),
        ),
        migrations.AlterField(
            model_name='surveytest',
            name='time_passing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время прохождения в минутах'),
        ),
    ]
