# Generated by Django 4.1.7 on 2023-04-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_base', '0003_alter_isurvey_options_alter_surveysimple_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isurvey',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
