# Generated by Django 4.1.7 on 2023-04-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_base', '0005_rename_is_published_isurvey_option_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isurvey',
            name='option_is_published',
            field=models.BooleanField(blank=True, default=False, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='isurvey',
            name='option_only_for_register_users',
            field=models.BooleanField(blank=True, default=False, verbose_name='Необходимость авторизации'),
        ),
        migrations.AlterField(
            model_name='isurvey',
            name='slug',
            field=models.SlugField(blank=True, max_length=108, null=True, unique=True),
        ),
    ]
